Repository SwissBitcoinPay/boltcard-tools-terminal, pull requests merged in 2024-01, with the labels that each got.

#15 Fix/scan crash
  .env
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/org/boltcardtools/terminal/MainApplication.kt
  android/gradle.properties
  codemagic.yaml
  package-lock.json
  package.json
  patches/@react-native-clipboard+clipboard+1.12.1.patch
  patches/react-native-encrypted-storage+4.0.3.patch
  react-native.config.js
  src/components/QRCamera/QRCamera.native.tsx
  src/components/QRCamera/types.ts
  src/screens/QRScanner/QRScanner.tsx
Labels: bug

#16 initial check clipboard
  .env
  src/assets/translations/en.json
  src/components/ComponentStack/ComponentStack.tsx
  src/components/Pressable/Pressable.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/styled.ts
  src/hooks/index.ts
  src/hooks/useInitialClipboard.ts
  src/hooks/useInvoiceHandler.ts
  src/screens/Home/Home.tsx
  src/screens/Invoice/Invoice.tsx
  src/types/index.ts
  src/utils/getBitcoinInvoiceData.ts
  src/utils/index.ts
Labels: enhancement

#17 Remove useless packages
  .env
  package-lock.json
  package.json
  patches/@react-native+eslint-config+0.73.2.patch
  patches/bcrypt-react-native+1.1.1.patch
  patches/js-crypto-env+1.0.5.patch
  patches/react-native-biometrics+3.0.1.patch
  patches/react-native-randombytes+3.6.1.patch
  patches/react-native-securerandom+1.0.1.patch
  patches/xpub-converter+1.0.2.patch
  src/assets/translations/en.json
  src/components/BitcoinLoader/BitcoinLoader.tsx
  src/components/BitcoinLoader/index.ts
  src/components/Loader/styled.ts
  src/components/QR/index.tsx
  src/components/QR/styled.ts
  src/components/index.ts
  src/utils/AsyncStorage/AsyncStorage.native.ts
  src/utils/AsyncStorage/AsyncStorage.ts
  src/utils/AsyncStorage/index.ts
  src/utils/generateBtcAddress/generateBtcAddress.ts
  src/utils/generateBtcAddress/getRandom/getRandom.native.ts
  src/utils/generateBtcAddress/getRandom/getRandom.ts
  src/utils/generateBtcAddress/getRandom/index.ts
  src/utils/generateBtcAddress/index.ts
  src/utils/getSha256.ts
  src/utils/index.ts
  webpack.config.ts
Labels: dependencies
